
appname: apache
replicaCount: 3
image:
  repository: docker.io/bitnami/apache
  tag: 2.4.41-debian-10-r29
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetport: 8080
  nodeport: 31228
  servicename: httpd-service

pvc:
  accessmodes: ReadWriteOnce
  request: 1Gi
  claimname: myhttpdclaim

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      path: /webserver
  tls: []

resources: 
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

serviceAccount:
  create: false

nodeSelector: {}

tolerations: []

affinity: {}
